### ISSUE TITLE
Navigation keys with fixed position

### ISSUE THREAD

**Issue by grigorisg9gr** [menpo/landmarker.io#90]
The position of the navigation keys (previous/next asset) is fixed in case the images have similar size, however it fluctuates greatly in case of different sizes per asset. This can be a bit tricky in case you want to review the images. For instance, you might oscillate between two images, since the 'next' button of an asset might coincide with the 'previous' button of the next asset. E.g. http://bit.ly/1ITl1TU

Therefore, it would be good to have these keys in some fixed position, e.g. in the middle of the images, regardless of the size of the frames.

**Comment by jabooth** [comment]
linked image so it's kept documented:
![landmarker_issue](https://cloud.githubusercontent.com/assets/1312873/7772418/f3d44b56-0095-11e5-891e-004ca21a77a2.png)

@lirsacc: interesting issue @grigorisg9gr is seeing - the middle flexbox (containing the paging keys) should always been centred. If you want to take a look whilst looking into the other layout bug that would be great.

**Comment by lirsacc** [comment]
This happens because the left flex is not fixed width and adapts to the asset id text, not related to image width though.

Easy to fix to lock the arrows in place, but the left UI still risks overflowing horizontally so I would propose either putting the index before the id or below (to be consistent for any length and avoid having it in the middle of the second line). Any preference @jabooth ?

**Comment by jabooth** [comment]
Ah of course! Let's go with the second solution - index below asset id.
